services:

  drupal: 
    image: drupal:10.4.6
    ports:
      - 8080:80

  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - ./mysql:/var/lib/mysql