services:
  rabbit:
    image:
      rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build: ./comunicacion-rabbitmq-ejem3-producer
    environment:
      - SPRING_RABBITMQ_HOST=rabbit

  consumer:
    build: ./comunicacion-rabbitmq-ejem3-consumer
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
      - SERVER_PORT=8080
