apiVersion: 1

datasources:
  - name: Prometheus-Lab
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Nombre del servicio en docker-compose
    isDefault: true
    editable: true